[terminal]
vt = 1

[default_session]
command = "agreety --cmd /home/alepez/.dotfiles/bin/start-hyprland"
user = "greeter"

[initial_session]
command = "/home/alepez/.dotfiles/bin/start-hyprland"
user = "alepez"
